// Datos de Códigos Postales de la Zona Metropolitana de Guadalajara (ZMG)
// Fuente: SEPOMEX - Servicio Postal Mexicano
// Municipios incluidos: Guadalajara, Zapopan, Tlaquepaque, Tonalá,
//   Tlajomulco de Zúñiga, El Salto, Ixtlahuacán de los Membrillos, Juanacatlán, Zapotlanejo
//
// Para expandir: descargar datos completos de https://www.correosdemexico.gob.mx/SSLServicios/ConsultaCP/CodigoPostal_Exportar.aspx
// y filtrar por estado "Jalisco" y los municipios de la ZMG.

const zmgPostalCodes = {
  // ===================== GUADALAJARA =====================
  "44100": { colonias: ["Centro", "Analco", "San Juan de Dios"], municipio: "Guadalajara" },
  "44101": { colonias: ["Mexicaltzingo"], municipio: "Guadalajara" },
  "44110": { colonias: ["Barrio de San Sebastián de Analco", "San Sebastián de Analco"], municipio: "Guadalajara" },
  "44120": { colonias: ["Americana", "Lafayette", "Arcos Vallarta"], municipio: "Guadalajara" },
  "44130": { colonias: ["Artesanos", "El Retiro"], municipio: "Guadalajara" },
  "44140": { colonias: ["Jardines del Bosque", "Providencia"], municipio: "Guadalajara" },
  "44150": { colonias: ["Chapalita", "Chapalita Sur", "Chapalita Oriente", "Chapalita Inn"], municipio: "Guadalajara" },
  "44160": { colonias: ["Monraz", "Lomas del Country", "Lomas de Providencia"], municipio: "Guadalajara" },
  "44170": { colonias: ["Lomas de Guevara", "Colomos Providencia"], municipio: "Guadalajara" },
  "44180": { colonias: ["Italia Providencia", "Providencia 1a Sección", "Providencia 2a Sección"], municipio: "Guadalajara" },
  "44190": { colonias: ["Ladrón de Guevara", "Circunvalación Vallarta"], municipio: "Guadalajara" },
  "44200": { colonias: ["San Andrés", "Villaseñor", "Mezquitán Country", "Alcalde Barranquitas"], municipio: "Guadalajara" },
  "44210": { colonias: ["Barrera", "Lomas de Independencia"], municipio: "Guadalajara" },
  "44220": { colonias: ["División del Norte", "Belisario Domínguez"], municipio: "Guadalajara" },
  "44230": { colonias: ["Santa Teresita", "Barrio de Santa Teresita"], municipio: "Guadalajara" },
  "44240": { colonias: ["Independencia", "Independencia Oriente"], municipio: "Guadalajara" },
  "44250": { colonias: ["Reforma", "Libertad"], municipio: "Guadalajara" },
  "44260": { colonias: ["Blanco y Cuéllar", "Huentitán El Bajo"], municipio: "Guadalajara" },
  "44270": { colonias: ["Huentitán El Alto", "Lomas de Huentitán"], municipio: "Guadalajara" },
  "44280": { colonias: ["Oblatos", "La Perla"], municipio: "Guadalajara" },
  "44290": { colonias: ["San Marcos", "Atlas"], municipio: "Guadalajara" },
  "44300": { colonias: ["San Carlos", "Echeverría"], municipio: "Guadalajara" },
  "44310": { colonias: ["Morelos", "Polanco"], municipio: "Guadalajara" },
  "44320": { colonias: ["Jardines Alcalde", "Alcalde Barranquitas"], municipio: "Guadalajara" },
  "44330": { colonias: ["Country Club", "Santa Mónica"], municipio: "Guadalajara" },
  "44340": { colonias: ["Heliodoro Hernández Loza", "Constitución"], municipio: "Guadalajara" },
  "44350": { colonias: ["La Nogalera", "Sector Libertad"], municipio: "Guadalajara" },
  "44360": { colonias: ["Lagos de Oriente", "Residencial Lagos"], municipio: "Guadalajara" },
  "44370": { colonias: ["Miravalle", "San Eugenio"], municipio: "Guadalajara" },
  "44380": { colonias: ["La Aurora", "El Dean"], municipio: "Guadalajara" },
  "44390": { colonias: ["San Onofre", "Autocinema"], municipio: "Guadalajara" },
  "44400": { colonias: ["Tetlán", "Tetlán Río Verde"], municipio: "Guadalajara" },
  "44410": { colonias: ["La Federacha", "Infonavit Río Nilo"], municipio: "Guadalajara" },
  "44420": { colonias: ["El Sauz", "El Sauz Bajo"], municipio: "Guadalajara" },
  "44430": { colonias: ["Lomas del Paraíso", "Lomas del Gallo"], municipio: "Guadalajara" },
  "44440": { colonias: ["Olímpica", "Residencial Olímpica"], municipio: "Guadalajara" },
  "44450": { colonias: ["San Martín de las Flores de Abajo"], municipio: "Guadalajara" },
  "44460": { colonias: ["Quinta Velarde", "18 de Marzo"], municipio: "Guadalajara" },
  "44470": { colonias: ["Hermosa Provincia", "San Martín"], municipio: "Guadalajara" },
  "44500": { colonias: ["Jardines de Guadalupe", "Lomas de Polanco"], municipio: "Guadalajara" },
  "44510": { colonias: ["Colinas de la Normal", "Santa Elena de la Cruz"], municipio: "Guadalajara" },
  "44520": { colonias: ["Jardines del Auditorio", "Agua Blanca Industrial"], municipio: "Guadalajara" },
  "44530": { colonias: ["El Fresno", "Residencial Juan Manuel"], municipio: "Guadalajara" },
  "44540": { colonias: ["Zona Industrial", "Parque Industrial El Álamo"], municipio: "Guadalajara" },
  "44550": { colonias: ["San Isidro", "San Isidro Ejidal"], municipio: "Guadalajara" },
  "44560": { colonias: ["Los Colorines", "San Isidro"], municipio: "Guadalajara" },
  "44570": { colonias: ["Constitución", "Del Fresno"], municipio: "Guadalajara" },
  "44580": { colonias: ["Colón Industrial", "San Marcos"], municipio: "Guadalajara" },
  "44600": { colonias: ["Jesús García", "La Normal"], municipio: "Guadalajara" },
  "44610": { colonias: ["Mezquitán", "Jardines de los Arcos"], municipio: "Guadalajara" },
  "44620": { colonias: ["Atemajac del Valle", "Lomas de Atemajac"], municipio: "Guadalajara" },
  "44630": { colonias: ["Jardines del Country", "Residencial Patria"], municipio: "Guadalajara" },
  "44640": { colonias: ["Arcos de Guadalupe", "Residencial Victoria"], municipio: "Guadalajara" },
  "44650": { colonias: ["San Joaquín", "Jardines de San Ignacio"], municipio: "Guadalajara" },
  "44660": { colonias: ["Lagos de Oriente"], municipio: "Guadalajara" },
  "44670": { colonias: ["El Briseño", "Balcones del Cuatro"], municipio: "Guadalajara" },
  "44680": { colonias: ["Echeverría", "Jardines de San José"], municipio: "Guadalajara" },
  "44690": { colonias: ["Medrano", "Villaseñor"], municipio: "Guadalajara" },
  "44700": { colonias: ["Lomas de Polanco", "Altagracia"], municipio: "Guadalajara" },
  "44710": { colonias: ["Abastos", "San Rafael"], municipio: "Guadalajara" },
  "44720": { colonias: ["La Esperanza", "Álamo Industrial"], municipio: "Guadalajara" },
  "44730": { colonias: ["San Pedrito", "Talpita"], municipio: "Guadalajara" },
  "44740": { colonias: ["Santa Cecilia", "Colinas de la Primavera"], municipio: "Guadalajara" },
  "44750": { colonias: ["San Andrés", "Pueblo Quieto"], municipio: "Guadalajara" },
  "44760": { colonias: ["San Marcos", "La Aurora"], municipio: "Guadalajara" },
  "44770": { colonias: ["Las Juntas", "5 de Mayo"], municipio: "Guadalajara" },
  "44800": { colonias: ["Sector Hidalgo", "Sector Juárez"], municipio: "Guadalajara" },
  "44810": { colonias: ["Sector Reforma", "Sector Libertad"], municipio: "Guadalajara" },
  "44820": { colonias: ["Moderna", "Santa Elena Estadio"], municipio: "Guadalajara" },
  "44840": { colonias: ["La Perla", "Las Conchas"], municipio: "Guadalajara" },
  "44860": { colonias: ["Jardines de La Cruz", "Jardines de la Paz"], municipio: "Guadalajara" },
  "44870": { colonias: ["Miravalle", "Lomas del Cuatro"], municipio: "Guadalajara" },
  "44900": { colonias: ["Haciendas de San José", "Revolución"], municipio: "Guadalajara" },
  "44910": { colonias: ["Hogares de Nuevo México", "Villas de San Juan"], municipio: "Guadalajara" },
  "44940": { colonias: ["Residencial Plaza Guadalupe"], municipio: "Guadalajara" },
  "44950": { colonias: ["Rancho Nuevo"], municipio: "Guadalajara" },
  "44960": { colonias: ["Lomas del Sur"], municipio: "Guadalajara" },
  "44970": { colonias: ["Toluquilla"], municipio: "Guadalajara" },
  "44980": { colonias: ["El Vergel"], municipio: "Guadalajara" },
  "44990": { colonias: ["Las Pintas"], municipio: "Guadalajara" },

  // ===================== ZAPOPAN =====================
  "45010": { colonias: ["Seattle", "Paseos del Sol"], municipio: "Zapopan" },
  "45014": { colonias: ["Loma Bonita Ejidal"], municipio: "Zapopan" },
  "45015": { colonias: ["Colinas de San Javier"], municipio: "Zapopan" },
  "45017": { colonias: ["Los Gavilanes", "Rinconada de los Gavilanes"], municipio: "Zapopan" },
  "45019": { colonias: ["Ciudad Bugambilias"], municipio: "Zapopan" },
  "45020": { colonias: ["Jardines del Sol", "Jardines de Tabachines"], municipio: "Zapopan" },
  "45030": { colonias: ["Jardines de Santa Isabel", "Villa de los Belenes"], municipio: "Zapopan" },
  "45040": { colonias: ["Ciudad del Sol", "El Mante", "La Estancia"], municipio: "Zapopan" },
  "45050": { colonias: ["Arcos de Zapopan", "Arcos Sur"], municipio: "Zapopan" },
  "45060": { colonias: ["Jardín Real", "Real de Valdepeñas"], municipio: "Zapopan" },
  "45066": { colonias: ["Hacienda Real", "Haciendas del Real"], municipio: "Zapopan" },
  "45067": { colonias: ["Parque Industrial Belenes"], municipio: "Zapopan" },
  "45068": { colonias: ["Lomas de Zapopan", "Tepeyac"], municipio: "Zapopan" },
  "45069": { colonias: ["Los Robles"], municipio: "Zapopan" },
  "45070": { colonias: ["Chapalita", "Lomas del Bosque"], municipio: "Zapopan" },
  "45079": { colonias: ["Pinar de la Calma"], municipio: "Zapopan" },
  "45080": { colonias: ["Rinconada del Bosque", "Del Bosque"], municipio: "Zapopan" },
  "45086": { colonias: ["Rinconada de la Azalea"], municipio: "Zapopan" },
  "45089": { colonias: ["El Colli Urbano"], municipio: "Zapopan" },
  "45090": { colonias: ["Residencial Poniente", "Las Águilas"], municipio: "Zapopan" },
  "45100": { colonias: ["Tepeyac Casino", "Constitución"], municipio: "Zapopan" },
  "45110": { colonias: ["La Tuzanía", "Tuzanía Ejidal"], municipio: "Zapopan" },
  "45116": { colonias: ["Las Palmas", "La Palmera"], municipio: "Zapopan" },
  "45120": { colonias: ["Colli CTM", "Valle de los Molinos"], municipio: "Zapopan" },
  "45130": { colonias: ["Residencial San Elías", "Nuevo México"], municipio: "Zapopan" },
  "45136": { colonias: ["Residencial Universidad"], municipio: "Zapopan" },
  "45138": { colonias: ["El Colli Ejidal"], municipio: "Zapopan" },
  "45140": { colonias: ["Santa Margarita", "Santa Margarita Primera Sección"], municipio: "Zapopan" },
  "45150": { colonias: ["La Calma", "Tabachines"], municipio: "Zapopan" },
  "45157": { colonias: ["La Primavera"], municipio: "Zapopan" },
  "45160": { colonias: ["El Vigía", "La Martinica"], municipio: "Zapopan" },
  "45170": { colonias: ["Zapopan Centro", "Zapopan"], municipio: "Zapopan" },
  "45180": { colonias: ["San Juan de Ocotán", "Residencial Victoria"], municipio: "Zapopan" },
  "45188": { colonias: ["Santa Ana Tepetitlán"], municipio: "Zapopan" },
  "45190": { colonias: ["La Venta del Astillero"], municipio: "Zapopan" },
  "45200": { colonias: ["Atemajac de Brizuela", "San Esteban"], municipio: "Zapopan" },
  "45203": { colonias: ["Valle de las Heras", "Parque Industrial Zapopan Norte"], municipio: "Zapopan" },
  "45206": { colonias: ["Base Aérea Militar No. 5"], municipio: "Zapopan" },
  "45210": { colonias: ["Tesistán", "Santa Cruz del Valle"], municipio: "Zapopan" },
  "45220": { colonias: ["Nextipac"], municipio: "Zapopan" },
  "45221": { colonias: ["Villas de Guadalupe", "Los Girasoles"], municipio: "Zapopan" },
  "45230": { colonias: ["Copala"], municipio: "Zapopan" },
  "45236": { colonias: ["Parque Industrial Los Belenes"], municipio: "Zapopan" },
  "45238": { colonias: ["Agua Fría"], municipio: "Zapopan" },

  // ===================== TLAQUEPAQUE =====================
  "45500": { colonias: ["San Pedro Tlaquepaque Centro", "Tlaquepaque Centro"], municipio: "San Pedro Tlaquepaque" },
  "45510": { colonias: ["Las Huertas", "Niños Héroes"], municipio: "San Pedro Tlaquepaque" },
  "45520": { colonias: ["La Duraznera", "La Gigantera"], municipio: "San Pedro Tlaquepaque" },
  "45530": { colonias: ["Lomas de San Miguel", "San Miguel de la Colina"], municipio: "San Pedro Tlaquepaque" },
  "45540": { colonias: ["Las Juntas", "El Tapatío"], municipio: "San Pedro Tlaquepaque" },
  "45547": { colonias: ["Parques de Santa Cruz del Valle"], municipio: "San Pedro Tlaquepaque" },
  "45550": { colonias: ["Toluquilla", "Fraccionamiento Revolución"], municipio: "San Pedro Tlaquepaque" },
  "45559": { colonias: ["Santa María Tequepexpan"], municipio: "San Pedro Tlaquepaque" },
  "45560": { colonias: ["Loma Dorada", "Loma Dorada Oriente"], municipio: "San Pedro Tlaquepaque" },
  "45570": { colonias: ["Los Meseros", "El Sauz"], municipio: "San Pedro Tlaquepaque" },
  "45580": { colonias: ["San Martín de las Flores de Abajo"], municipio: "San Pedro Tlaquepaque" },
  "45590": { colonias: ["San Martín de las Flores de Arriba"], municipio: "San Pedro Tlaquepaque" },
  "45593": { colonias: ["La Ladrillera"], municipio: "San Pedro Tlaquepaque" },
  "45598": { colonias: ["Santa Anita"], municipio: "San Pedro Tlaquepaque" },
  "45600": { colonias: ["El Álamo", "Las Liebres"], municipio: "San Pedro Tlaquepaque" },
  "45601": { colonias: ["Las Pintitas"], municipio: "San Pedro Tlaquepaque" },
  "45604": { colonias: ["Miravalle"], municipio: "San Pedro Tlaquepaque" },
  "45609": { colonias: ["San Pedrito"], municipio: "San Pedro Tlaquepaque" },
  "45615": { colonias: ["La Duraznera"], municipio: "San Pedro Tlaquepaque" },
  "45619": { colonias: ["López Cotilla", "La Loma"], municipio: "San Pedro Tlaquepaque" },
  "45625": { colonias: ["Santa Fe", "Las Liebres"], municipio: "San Pedro Tlaquepaque" },
  "45630": { colonias: ["Lomas del Cuatro"], municipio: "San Pedro Tlaquepaque" },
  "45640": { colonias: ["Cerro del Cuatro"], municipio: "San Pedro Tlaquepaque" },

  // ===================== TONALÁ =====================
  "45400": { colonias: ["Tonalá Centro", "Tonalá"], municipio: "Tonalá" },
  "45401": { colonias: ["El Rosario"], municipio: "Tonalá" },
  "45402": { colonias: ["Jalisco"], municipio: "Tonalá" },
  "45403": { colonias: ["Lomas de Tonalá"], municipio: "Tonalá" },
  "45404": { colonias: ["Colinas de Tonalá"], municipio: "Tonalá" },
  "45405": { colonias: ["La Punta", "Cañada de los Gallos"], municipio: "Tonalá" },
  "45406": { colonias: ["San Gaspar de las Flores"], municipio: "Tonalá" },
  "45407": { colonias: ["Coyula"], municipio: "Tonalá" },
  "45408": { colonias: ["Puente Grande"], municipio: "Tonalá" },
  "45410": { colonias: ["Basilio Badillo", "El Vado"], municipio: "Tonalá" },
  "45411": { colonias: ["Arroyo de En Medio"], municipio: "Tonalá" },
  "45412": { colonias: ["La Loma", "La Loma Chica"], municipio: "Tonalá" },
  "45414": { colonias: ["Lomas del Camichín"], municipio: "Tonalá" },
  "45416": { colonias: ["Hacienda de Tonalá"], municipio: "Tonalá" },
  "45417": { colonias: ["Jauja"], municipio: "Tonalá" },
  "45418": { colonias: ["Zalatitán"], municipio: "Tonalá" },
  "45420": { colonias: ["San Sebastianito"], municipio: "Tonalá" },
  "45425": { colonias: ["Residencial Tonalá", "Tateposco"], municipio: "Tonalá" },

  // ===================== TLAJOMULCO DE ZÚÑIGA =====================
  "45640": { colonias: ["Cerro del Cuatro"], municipio: "Tlajomulco de Zúñiga" },
  "45641": { colonias: ["Hacienda Santa Fe", "Santa Fe"], municipio: "Tlajomulco de Zúñiga" },
  "45643": { colonias: ["El Palomar", "Chulavista"], municipio: "Tlajomulco de Zúñiga" },
  "45644": { colonias: ["La Piedrera"], municipio: "Tlajomulco de Zúñiga" },
  "45645": { colonias: ["Las Víboras"], municipio: "Tlajomulco de Zúñiga" },
  "45646": { colonias: ["La Tijera", "Hacienda La Tijera"], municipio: "Tlajomulco de Zúñiga" },
  "45647": { colonias: ["San Agustín"], municipio: "Tlajomulco de Zúñiga" },
  "45648": { colonias: ["Valle Real"], municipio: "Tlajomulco de Zúñiga" },
  "45649": { colonias: ["El Fortín"], municipio: "Tlajomulco de Zúñiga" },
  "45650": { colonias: ["Tlajomulco de Zúñiga Centro", "Tlajomulco"], municipio: "Tlajomulco de Zúñiga" },
  "45653": { colonias: ["Chulavista", "Santa Cruz de las Flores"], municipio: "Tlajomulco de Zúñiga" },
  "45654": { colonias: ["Fraccionamiento Urbi Quinta Montecarlo"], municipio: "Tlajomulco de Zúñiga" },
  "45655": { colonias: ["San Sebastián el Grande"], municipio: "Tlajomulco de Zúñiga" },
  "45659": { colonias: ["Cajititlán"], municipio: "Tlajomulco de Zúñiga" },

  // ===================== EL SALTO =====================
  "45680": { colonias: ["El Salto Centro", "El Salto"], municipio: "El Salto" },
  "45681": { colonias: ["Las Pintas de Arriba"], municipio: "El Salto" },
  "45682": { colonias: ["Las Pintitas"], municipio: "El Salto" },
  "45685": { colonias: ["San José del Castillo"], municipio: "El Salto" },
  "45690": { colonias: ["El Verde"], municipio: "El Salto" },
  "45693": { colonias: ["Parque Industrial El Salto"], municipio: "El Salto" },
  "45694": { colonias: ["Juanacatlán"], municipio: "El Salto" },

  // ===================== IXTLAHUACÁN DE LOS MEMBRILLOS =====================
  "45850": { colonias: ["Ixtlahuacán de los Membrillos"], municipio: "Ixtlahuacán de los Membrillos" },
  "45852": { colonias: ["Atequiza"], municipio: "Ixtlahuacán de los Membrillos" },

  // ===================== JUANACATLÁN =====================
  "45880": { colonias: ["Juanacatlán"], municipio: "Juanacatlán" },

  // ===================== ZAPOTLANEJO =====================
  "45430": { colonias: ["Zapotlanejo Centro", "Zapotlanejo"], municipio: "Zapotlanejo" },
  "45432": { colonias: ["Matatlán"], municipio: "Zapotlanejo" },
};

// Lista de municipios válidos de la ZMG
const zmgMunicipios = [
  "Guadalajara",
  "Zapopan",
  "San Pedro Tlaquepaque",
  "Tonalá",
  "Tlajomulco de Zúñiga",
  "El Salto",
  "Ixtlahuacán de los Membrillos",
  "Juanacatlán",
  "Zapotlanejo",
];

export { zmgPostalCodes, zmgMunicipios };
